I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 298, in script
    if memo:
  File "game/script.rpy", line 298, in <module>
    if memo:
NameError: name 'memo' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 298, in script
    if memo:
  File "D:\Renpy\renpy-6.99.13-sdk\renpy\ast.py", line 1681, in execute
    if renpy.python.py_eval(condition):
  File "D:\Renpy\renpy-6.99.13-sdk\renpy\python.py", line 1794, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Renpy\renpy-6.99.13-sdk\renpy\python.py", line 1788, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 298, in <module>
    if memo:
NameError: name 'memo' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.13.2919
Melody 1.0
