I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 68, in script
    m "wendy，借你实验报告我看看？懒得写啦"
Exception: Sayer 'm' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 68, in script
    m "wendy，借你实验报告我看看？懒得写啦"
  File "D:\Renpy\renpy-6.99.13-sdk\renpy\ast.py", line 596, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\Renpy\renpy-6.99.13-sdk\renpy\ast.py", line 509, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'm' is not defined.

Windows-8-6.2.9200
Ren'Py 6.99.13.2919
Melody 1.0
